version: "3.1"
services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timeuse-db
    ports:
      - 5433:5432
    restart: always
