version: "3.1"
services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tus
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
#      - ./init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgresdb:
