spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/timeuse-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 9100

contact-io:
  url: http://localhost:9101/v1/send
  enabled: false
#
#flyway:
#  baseline-on-migrate=true:
