spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tus
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

spring.main.banner-mode: off
management.endpoints.web.exposure.include: health, metrics, prometheus

contact-io:
#  url: ${CONTACT_IO_URL}
  enabled: true
  url: http:dummyhttp.ssb
