webserver:
  host: 0.0.0.0
  port: 10140
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"


spring:
  # Don't print the Spring logo banner at startup (We want only JSON logs printed to stdout)
  main:
    banner-mode: off
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tidsbruk-db
    driver-class-name: org.postgresql.Driver
    username: dummy_value
    password: dummy_value
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 9100

springdoc:
  api-docs:
    path: /api-docs

management.endpoints.web.exposure.include: health, metrics, prometheus

contact-io:
#  url: ${CONTACT_IO_URL}
  enabled: true
  url: http:dummyhttp.ssb
